node:
  identity:
    id: bdb-node-1
    certificatePath: ./testdata/node.cert
    keyPath: ./testdata/node.key
  network:
    address: 127.0.0.1
    port: 6001
  database:
    name: leveldb
    ledgerDirectory: ./tmp/

admin:
  id: admin
  certificatePath: ./testdata/admin.cert

rootca:
  certificatePath: ./testdata/rootca.cert
