server:
  id: bdb-node-1
  network:
    address: 127.0.0.1
    port: 6001
  identity:
    certificate: node1.crt
    key: node1.key
  database:
    name: leveldb
    ledgerDirectory: ./tmp/

rootca:
  certificate: ca.crt

admin:
  username: admin
  dbname: admin
  certificate: admin.crt
