server:
  id: bdb-node-1
  network:
    address: localhost
    port: 6001
  crypto:
    certificate: peer1.crt
    key: peer1.key
  database:
    name: leveldb
    ledgerDirectory: ./tmp/

rootca:
  certificate: ca.crt

admin:
  username: admin
  dbname: admin
  certificate: admin.crt
